<?php

use App\Destination;
use App\Role;
use App\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    private $tables = [
        'users','reservations','roles','role_user', 'destinations','vehicles'
    ];
    
    /**
     * Run the database seeds.
     *
     * @return void
     */
    private $destinations = ["VILLAS NAUTILUS TAMARINDO","HOTEL  TAMARINDO DIRIA","VILLA ARTEMIS TAMARINDO","CASA TAMARINDO","MANGO CONDO TAMARINDO","TAMARINDO BACKPACKERS HOSTEL","BOCA RACA TAMARINDO","VILLA VERDE 1 CONDOS TAMARINDO","VILLA VERDE 2 CONDOS TAMARINDO","PURA VIDA MINI HOSTEL TAMARINDO","OVEJA NEGRA HOSTEL TAMARINDO","CORAL REEF HOSTEL TAMARINDO","ESTRELLAS DEL PACIFICO CONDOS TAMARINDO","THE OAKS CONDOS - HUACAS","HOTEL ESPLENDOR TAMARINDO","HOTEL MAR REY TAMARINDO","CASA BAMBORA TAMARINDO","PUEBLO DEL MAR CONDOS TAMARINDO","CASA SUNSET TAMARINDO","CABINAS TSUNAMI TAMARINDO","BAHIA LANGOSTA CONDOS","MONTEPERLA CONDOS TAMARINDO","CASA TROPICAL LANGOSTA","CASA BLANCA LANGOSTA","EL GRAN MIRADOR TAMARINDO","HOTEL LUNA LLENA TAMARINDO","CASA MATALAO TAMARINDO","DIRIA CONDOS TAMARINDO","LA PERLA CONDOS TAMARINDO","BLUE TRAILZ HOTEL TAMARINDO","TAMARINDO BAY HOTEL","CASA SONRISA LANGOSTA","BOKAS RESTAURANT LANGOSTA","TAMARINDO PRESERVE - LANGOSTA","PURA VIDA HOSTEL TAMARINDO","LONGBOARDS HOSTEL TAMARINDO","PACIFIC PARK CONDOS TAMARINDO","PENINSULA CONDOS. LANGOSTA","CASA EL BOSQUE TAMARINDO","HARRYS EL ESCONDITE HOTEL TAMARINDO","HOTEL MONO LOCO TAMARINDO","CASA DE ARROZ TAMARINDO","LA BOTELLA DE LECHE HOSTEL TAMARINDO","VILLA MARIPOSA TAMARINDO","HOTEL VILLA AMARILLA TAMARINDO,","HOTEL JARDIN DEL EDEN TAMARINDO","EL LABRADOR APARTMENTS TAMARINDO","HOTEL IN THE SHADE TAMARINDO","CASA TIBURON SURFHOUSE TAMARINDO","CASA PAPAYA TAMARINDO","CABINAS MARIELOS TAMARINDO","IGUANA SURF CONDOS TAMARINDO","HOTEL GARDENIA TAMARINDO","PANGAS RESTAURANTE TAMARINDO","HOTEL CALA LUNA TAMARINDO","LA ESQUINA CONDOS LANGOSTA","CASA GIA","HOTEL MAMIRI TAMARINDO","CASA PIZOTE -LANGOSTA","LEORA DEL PACIFICO CONDOS TAMARINDO","HOTEL PUEBLO DORADO TAMARINDO","LOS SUEÑOS 1 CONDOS TAMARINDO","LOS SUEÑOS 2 CONDOS TAMARINDO","LOS SUEÑOS 3 CONDOS TAMARINDO","CASA DE LAS OLAS TAMARINDO","HOTEL BEST WESTERNS TAMARINDO VISTA VILLAS","CASA ELERI TAMARINDO","APARTAMENTOS LAS PALMAS TAMARINDO","HOTEL LAGUNA DE COCODRILO TAMARINDO","SUNRISE CONDOS TAMARINDO","TAMARINDO GYM APARTMENTS","BAHIA LANGOSTA CONDOS","CASA TRANQUILA TAMARINDO","HOTEL CHOCOLATE TAMARINDO","HOTEL NAHUA TAMARINDO","TAMARINDO HOSTEL RESORT","VILLAS GUAPINOL LANGOSTA","VIA PARAISO TAMARINDO","CASA SMILING DOG TAMARINDO","HORIZONTES DEL MAR LANGOSTA","VILLAS VALENCIA DEL MAR LANGOSTA","CASA COLONIAL TAMARINDO","T.T.T OFFICE","MARATONGA HUACAS","SAN DOLLAR CONDOS TAMARINDO","NAXOS CONDOS LANGOSTA","CASA LEONA TAMARINDO","VILLAS PORTOFINO TAMARINDO","CASA ELA TAMARINDO","SOLES Y MARGARITAS CONDOS TAMARINDO","HOTEL SUEÑO DEL MAR LANGOSTA","COMACO HUACAS","CASA LUNA","EL COMETA CONDOS TAMARINDO","CASA LA BRUJA LANGOSTA", "INDRA INN PL.GRANDE","PLAYA GRANDE SURF CAMP","HACIENDA PINILLA RESERVA DE GOLF","JW MARRIOTT HOTEL","HAC PINILLA LAGOS DE PALMA"];

    public function run()
    {
         $this->cleanDatabase();

        factory(Role::class, 1)->create();
        factory(Role::class, 1)->create([
            'name' => 'agent',
        ]);
        

        foreach ($this->destinations as $s) {
            factory(Destination::class, 1)->create([
                'name' => $s,
            ]);
        }

        factory(User::class, 1)->create([
            'name' => 'admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt('123456'),
            'remember_token' => str_random(10),
        ]);

         DB::table('role_user')->insert(['role_id'=>1, 'user_id'=>1]);

    }

     private function cleanDatabase()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        foreach ($this->tables as $tablename) {
            DB::table($tablename)->truncate();
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
